### ISSUE TITLE
Can RequestCode onActivityResult be changed to something else

### ISSUE THREAD

**Issue by vijay559** [Azure-Samples/active-directory-android-native-v2#10]
/* Handles the redirect from the System Browser */
    @Override
    protected void onActivityResult(int requestCode, int resultCode, Intent data) {
        sampleApp.handleInteractiveRequestRedirect(requestCode, resultCode, data);
    }

The requestCode is by default 1001. Is there a way we can customize the requestCode to something else. I am using ADAL library and MSAL library, both these libraries doesn't give an option to change it to something else. When onActivityResult gets invoked, we end up getting the same requestCode.

**Comment by danieldobalian** [comment]
moving to the Auth library source -> https://github.com/AzureAD/microsoft-authentication-library-for-android/issues/421
