### ISSUE TITLE
Support Android SDK 21

### ISSUE THREAD

**Issue by ngmeiji08** [Azure-Samples/active-directory-android-native-v2#7]
Hi,Can Azure AD enhance to support android SDK 21 below ? Thanks

**Comment by danieldobalian** [comment]
We are planning on supporting versions lower than 21 before MSAL reaches GA. What's the min version you would be interested for your app?

**Comment by ngmeiji08** [comment]
4.4 Kitkat SDK 19

**Comment by danieldobalian** [comment]
Our next version of MSAL will support this or lower. Closing issue, can track at: https://github.com/AzureAD/microsoft-authentication-library-for-android/issues/263
